"""
Code exporters for QNN models.

Given a :class:`QNNModel` config (encoder name, ansatz name, num_qubits,
layers, feature_dim, observable), emit a ready-to-run Python snippet for
PennyLane and Qiskit-Machine-Learning.

The exports target the *current* trained parameters so a notebook can
reproduce the decision boundary exactly. Code is rendered as a string —
the route layer returns it inside a JSON payload.
"""

from __future__ import annotations

from textwrap import dedent
from typing import Iterable

import numpy as np

from .models import QNNModel


def _format_param_array(theta: np.ndarray) -> str:
    """Render a 1D float array as a compact Python literal."""
    items = ", ".join(f"{float(t):.6f}" for t in theta)
    return f"[{items}]"


# ─── PennyLane ────────────────────────────────────────────────────────────────
def to_pennylane(model: QNNModel, theta: np.ndarray) -> str:
    n = model.num_qubits
    enc = model.encoder.name
    layers = max(1, model.ansatz.num_params // (n if "real_amplitudes" in model.ansatz.name else 3 * n))
    is_real = model.ansatz.name.startswith("real_amplitudes")

    if is_real:
        ansatz_block = dedent(f"""
            for L in range({layers}):
                for q in range({n}):
                    qml.RY(theta[L * {n} + q], wires=q)
                if L < {layers - 1}:
                    for q in range({n} - 1):
                        qml.CNOT(wires=[q, q + 1])
        """).strip()
    else:
        ansatz_block = dedent(f"""
            idx = 0
            for L in range({layers}):
                for q in range({n}):
                    qml.RZ(theta[idx], wires=q); idx += 1
                    qml.RY(theta[idx], wires=q); idx += 1
                    qml.RZ(theta[idx], wires=q); idx += 1
                for q in range({n}):
                    qml.CNOT(wires=[q, (q + 1) % {n}])
        """).strip()

    if enc == "angle":
        encoder_block = f"for q in range({n}): qml.RY(np.pi * x[q], wires=q)"
    elif enc == "amplitude":
        encoder_block = f"qml.AmplitudeEmbedding(x, wires=range({n}), normalize=True)"
    else:  # zz_feature_map
        encoder_block = dedent(f"""
            for q in range({n}): qml.Hadamard(wires=q)
            for q in range({n}): qml.RZ(2.0 * x[q], wires=q)
            for q1 in range({n}):
                for q2 in range(q1 + 1, {n}):
                    qml.CNOT(wires=[q1, q2])
                    qml.RZ(2.0 * (np.pi - x[q1]) * (np.pi - x[q2]), wires=q2)
                    qml.CNOT(wires=[q1, q2])
        """).strip()

    code = dedent(f"""
        # Auto-generated by Qcuit QML Lab
        # encoder={enc}, ansatz={model.ansatz.name}, num_qubits={n}
        import numpy as np
        import pennylane as qml

        dev = qml.device('default.qubit', wires={n})
        theta = np.array({_format_param_array(theta)})

        @qml.qnode(dev)
        def circuit(x, theta):
            # ── Encoder ────────────────────────────────────────────────
            {encoder_block}
            # ── Ansatz ─────────────────────────────────────────────────
            {ansatz_block}
            return qml.expval(qml.PauliZ(0))

        # Example use:
        #   x = np.zeros({model.feature_dim})
        #   yhat = circuit(x, theta)
    """).strip() + "\n"
    return code


# ─── Qiskit Machine Learning ─────────────────────────────────────────────────
def to_qiskit_ml(model: QNNModel, theta: np.ndarray) -> str:
    n = model.num_qubits
    enc = model.encoder.name
    is_real = model.ansatz.name.startswith("real_amplitudes")
    layers = max(1, model.ansatz.num_params // (n if is_real else 3 * n))

    if enc == "angle":
        feature_map_line = (
            "from qiskit.circuit.library import PauliFeatureMap\n"
            f"feature_map = PauliFeatureMap(feature_dimension={model.feature_dim}, "
            f"reps=1, paulis=['Y'])"
        )
    elif enc == "zz_feature_map":
        feature_map_line = (
            "from qiskit.circuit.library import ZZFeatureMap\n"
            f"feature_map = ZZFeatureMap(feature_dimension={model.feature_dim}, reps=1)"
        )
    else:  # amplitude — Qiskit ML doesn't expose a direct AE feature map; emit comment.
        feature_map_line = (
            "# Amplitude encoding requires a custom QuantumCircuit with "
            "initialize().\nfrom qiskit import QuantumCircuit\n"
            f"feature_map = QuantumCircuit({n})  # TODO: initialize() per sample"
        )

    if is_real:
        ansatz_line = (
            "from qiskit.circuit.library import RealAmplitudes\n"
            f"ansatz = RealAmplitudes(num_qubits={n}, reps={max(1, layers - 1)})"
        )
    else:
        ansatz_line = (
            "from qiskit.circuit.library import EfficientSU2\n"
            f"ansatz = EfficientSU2(num_qubits={n}, reps={max(1, layers)}, entanglement='circular')"
        )

    code = dedent(f"""
        # Auto-generated by Qcuit QML Lab
        # encoder={enc}, ansatz={model.ansatz.name}, num_qubits={n}
        import numpy as np

        {feature_map_line}
        {ansatz_line}

        from qiskit_machine_learning.neural_networks import EstimatorQNN
        from qiskit.primitives import Estimator

        qnn = EstimatorQNN(
            circuit=feature_map.compose(ansatz),
            input_params=feature_map.parameters,
            weight_params=ansatz.parameters,
            estimator=Estimator(),
        )

        theta = np.array({_format_param_array(theta)})
        # Example use:
        #   x = np.zeros({model.feature_dim})
        #   yhat = qnn.forward(x, theta)[0][0]
    """).strip() + "\n"
    return code
